Add check for $OPAE_SDK_ROOT environment variable.

diff --git a/agilex7/iseries_pcie/ofs_build_env b/agilex7/iseries_pcie/ofs_build_env
--- a/agilex7/iseries_pcie/ofs_build_env
+++ b/agilex7/iseries_pcie/ofs_build_env
@@ -21,6 +21,11 @@ function check_opae_root() {
         echo "Error: The OPAE_PLATFORM_ROOT environment variable was not set.  Please ensure it points to an OFS FIM PR template."
         exit 1
     fi
+
+    if [ -z ${OPAE_SDK_ROOT:-} ]; then
+        echo "Error: The OPAE_SDK_ROOT environment variable was not set.  Please ensure it points to an OPAE installation."
+        exit 1
+    fi
 }
 
 function init_ofs_build_env() {
